[package]
name = "mork-frontend"
version = "0.1.0"
edition = "2021"

[dependencies]
pathmap = { workspace=true }
mork-bytestring = { workspace=true }
typed-arena = "2.0.2"
regex = "1.10.4"
memmap2 = "0.9.5"
